name: Build Debian Package

on:
  push:
    tags: [ "v*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -yq \
          build-essential clang clang-tools autotools-dev autoconf libtool \
          libgpod-dev \
          libglib2.0-dev \
          libavcodec-dev libavformat-dev libavfilter-dev libswscale-dev libavutil-dev \
          libjson-c-dev dh-make

      - name: Build deb
        run: fakeroot debian/rules binary

      - name: Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: ../gpod-utils_*.deb
