name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -yq \
        build-essential clang clang-tools autotools-dev autoconf libtool \
        libgpod-dev \
        libglib2.0-dev \
        libavcodec-dev libavformat-dev libavfilter-dev libswscale-dev libavutil-dev \
        libjson-c-dev

    - name: configure prep
      run: |
        autoreconf --install
        autoconf

    - name: build default
      run: |
        ./configure && make

    - name: build with sqlite3
      run: |
        sudo apt-get install -yq libsqlite3-dev
        ./configure && make clean && make

    - name: build with debug
      run: |
        make clean
        ./configure --enable-debug && make
